### ISSUE TITLE
TestClock.sleep(until deadline:) suspends when called with a deadline that is equal to TestClock.now

### ISSUE THREAD

**Issue by bobergj** [pointfreeco/swift-clocks#23]
### Description

TestClock.sleep(until deadline:) suspends when called with a deadline that is equal to TestClock.now

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-clocks/issues) or [discussion](https://github.com/pointfreeco/swift-clocks/discussions).

### Expected behavior

TestClock.sleep(until deadline:) immediately returns when TestClock.now is already equal to deadline

### Actual behavior

TestClock.sleep(until:) suspends if TestClock.now == deadline at the time of the call, clock must be advanced past the deadline for wake up

### Steps to reproduce

PR with test case and fix: https://github.com/pointfreeco/swift-clocks/pull/22

### swift-clocks version information

main

### Destination operating system

iOS 16

### Xcode version information

Version 14.3.1 (14E300c)

### Swift Compiler version information

```shell
xcrun swiftc --version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
```

**Comment by stephencelis** [comment]
Fixed by #22.

**Comment by bobergj** [comment]
@stephencelis I saw this was reverted: https://github.com/pointfreeco/swift-clocks/pull/26
but the revert doesn't provide a rationale. Doesn't reverted-to behaviour break the contract 
of  https://developer.apple.com/documentation/swift/task/sleep(until:tolerance:clock:), which is supposed to wake up at the deadline?

**Comment by stephencelis** [comment]
@bobergj Sorry for not describing the problem, but the change broke existing test clock tests and made `TestClock` behave differently than other test clocks and schedulers out there, including our combine-schedulers test scheduler, as well as the test schedulers that come with RxSwift, ReactiveSwift, and more.

A clock should suspend when told to sleep, and should only resume when the test clock advances. We do not believe this behavior breaks the contract because the test clock _does_ wake up at the deadline, it just needs to advance first, which is typically done by calling `clock.advance()` (which is an alias to `clock.advance(by: .seconds(0))`).
